"use client";
import {useState} from "react";
import {useRouter,useSearchParams} from "next/navigation";

export default function BookingForm({defaults}:{defaults:{name:string;nik:string;phone:string}}){
 const router=useRouter(),params=useSearchParams(); const initialService=params.get("serviceType")||"passenger"; const initialVehicle=params.get("vehicle")||initialService; const safeVehicle=([ "passenger","motor","car"] as const).includes(initialVehicle as "passenger"|"motor"|"car")?initialVehicle:"passenger"; const [name,setName]=useState(defaults.name),[nik,setNik]=useState(defaults.nik),[phone,setPhone]=useState(defaults.phone),[vehicle,setVehicle]=useState(safeVehicle),[plate,setPlate]=useState(params.get("vehiclePlate")||""),[error,setError]=useState(""),[busy,setBusy]=useState(false);
 const origin=params.get("origin")||"ujung",destination=params.get("destination")||"kamal",departureDate=params.get("departureDate")||new Date().toISOString().slice(0,10),serviceType=vehicle,price=vehicle==="motor"?15000:vehicle==="car"?20000:10000;
 async function submit(e:React.FormEvent){e.preventDefault();setError("");setBusy(true);const cleanName=name.trim(),cleanNik=nik.replace(/\D/g,""),cleanPhone=phone.replace(/\D/g,""),cleanPlate=plate.trim().toUpperCase();if(!/^\p{L}[\p{L}. ]+$/u.test(cleanName)){setError("Nama penumpang tidak valid.");setBusy(false);return}if(!/^\d{16}$/.test(cleanNik)){setError("NIK harus 16 digit.");setBusy(false);return}if(!/^08\d{8,11}$/.test(cleanPhone)){setError("Nomor telepon harus berformat 08.");setBusy(false);return}if((vehicle==="motor"||vehicle==="car")&&!/^[A-Z]{1,2} ?\d{4} ?[A-Z]+$/.test(cleanPlate)){setError("Format plat kendaraan tidak valid.");setBusy(false);return}const r=await fetch("/api/booking/draft",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({origin,destination,departureDate,serviceType,vehicle,passengerName:cleanName,passengerNik:cleanNik,passengerPhone:cleanPhone,vehiclePlate:cleanPlate})});const d=await r.json();if(!r.ok){setError(d.error||"Booking gagal.");setBusy(false);return}router.push("/payment?draft="+encodeURIComponent(d.draftId))}
 return <form onSubmit={submit} className="space-y-5">{error&&<div className="rounded-2xl border border-red-100 bg-red-50 px-4 py-3 text-sm font-semibold text-red-700">{error}</div>}
  <section className="aesthetic-card rounded-[2rem] p-5 sm:p-7"><div className="mb-6 flex items-center gap-3"><span className="flex h-10 w-10 items-center justify-center rounded-xl bg-[#27F5F5]/15 text-primary"><span className="material-symbols-outlined">person</span></span><div><p className="text-[10px] font-black uppercase tracking-wider text-[#00B4FF]">Step 01</p><h2 className="text-lg font-black text-primary">Data Penumpang</h2></div></div><div className="space-y-5"><Field label="Nama penumpang"><input value={name} onChange={e=>setName(e.target.value.replace(/[^\p{L}. ]/gu,"").replace(/\s+/g," "))} className="input" required/></Field><div className="grid gap-5 md:grid-cols-2"><Field label="NIK"><input value={nik} onChange={e=>setNik(e.target.value.replace(/\D/g,"").slice(0,16))} inputMode="numeric" className="input" required/></Field><Field label="Nomor HP"><input value={phone} onChange={e=>setPhone(e.target.value.replace(/\D/g,"").slice(0,13))} inputMode="numeric" className="input" required/></Field></div></div></section>
  <section className="aesthetic-card rounded-[2rem] p-5 sm:p-7"><div className="mb-6 flex items-center justify-between"><div><p className="text-[10px] font-black uppercase tracking-wider text-[#00B4FF]">Step 02</p><h2 className="text-lg font-black text-primary">Jenis Perjalanan</h2></div><span className="rounded-full bg-[#E0FF00]/50 px-3 py-1 text-[10px] font-black uppercase text-primary">Selected</span></div><div className="grid grid-cols-3 gap-3">{([[ "passenger","Jalan Kaki","directions_walk"],["motor","Motor","two_wheeler"],["car","Mobil","directions_car"]] as const).map(([id,label,icon])=><button type="button" key={id} onClick={()=>{setVehicle(id);setPlate("");}} className={`interactive-card flex flex-col items-center justify-center rounded-2xl border-2 py-4 ${vehicle===id?"border-[#00B4FF] bg-[#27F5F5]/10 text-primary shadow-sm":"border-slate-200 bg-white/70 text-slate-500"}`}><span className="material-symbols-outlined">{icon}</span><span className="mt-1 text-[10px] font-black uppercase">{label}</span></button>)}</div>{(vehicle==="motor"||vehicle==="car")&&<div className="mt-5"><Field label="Plat kendaraan"><input value={plate} onChange={e=>setPlate(e.target.value.toUpperCase().replace(/[^A-Z0-9 ]/g,"").replace(/\s+/g," "))} className="input" placeholder="KT 9899 LK" required/></Field></div>}</section>
  <div className="site-gradient sticky bottom-3 z-20 rounded-2xl p-4 text-white shadow-2xl shadow-blue-950/20"><div className="flex items-center justify-between gap-4"><div><p className="text-[10px] uppercase tracking-widest text-blue-200">Total sebelum service fee</p><p className="text-2xl font-black">IDR {price.toLocaleString("id-ID")}</p></div><button disabled={busy} className="accent-btn rounded-xl px-5 py-3 text-xs font-black uppercase tracking-widest disabled:opacity-60">{busy?"Membuat booking...":"Lanjut Bayar →"}</button></div></div>
 </form>
}
function Field({label,children}:{label:string;children:React.ReactNode}){return <label className="block"><span className="mb-2 block text-xs font-bold uppercase tracking-wider text-on-surface-variant">{label}</span>{children}</label>}
